### ISSUE TITLE
收藏的歌曲只能获取100页

### ISSUE THREAD

**Issue by GhostStar** [reorx/xiami_exporter#4]
首先感谢作者在百忙之中写出此救急工具，但是使用新版虾米接口的话收藏的歌曲只能获取到100页，如果收藏歌曲超过3000曲的话将会获取不到。

可以使用旧版收藏的歌曲页面进行获取，https://emumo.xiami.com/space/lib-song/u/{id}/page/1 ，不知道您是否有时间更新或使用其他方法解决此问题。

**Comment by reorx** [comment]
嗯，可以尝试这个思路，通过旧版页面获得 id 列表，然后用新版的 getSongs 获得新版的返回数据。

我最近在写 album cover 下载和 id3 tag 功能，预计明天就完工，然后就可以开始做这个功能了。

有两个问题：
- 触发这个限制的时候虾米是怎么返回的，可以把命令行的情况给我看一下吗？
- 你一共有多少首收藏歌曲？可能每页 30 个是可以突破的，我一会尝试一下，如果可以改大，比如 50 个，那么只要你的收藏不超过 5000 也许还可以用现在的方案。

**Comment by GhostStar** [comment]
1. 使用 export-songs 命令获取数据时，当超过 100 页时会继续获取下一页的数据，但是此时接口返回的每一页的数据都和 100 页一致且不会停止获取直至手动结束。
2. 刚才试了一下通过修改 get_fav_songs 的 page_size 为 100，测试下来是可以完成全部爬取的，我目前收藏有 3500 首左右但不确定超过 5000 是否可以使用此方案。

**Comment by reorx** [comment]
经尝试，一页最多可以有 100 个:

```
> XME_DIR_PATH=_exports python -m xiami_exporter.cli -d export-songs -p 1 -s 200
test fetch() ok
recal token correct: 6f5188417bca953c6d090dde6b5519a6
INFO:xiami.client:get_fav_songs: page=1
DEBUG:cli:get_fav_songs length 99
```

（某种虾米接口的未知原因导致第一页会比 page_size 少一个）

我已经增加了 `--page-size` 参数，应该可以应付你的情况，你可以尝试 `--page-size 100` 然后重新进行一次全量爬取，若有问题我们再看。

**Comment by reorx** [comment]
先关闭了，若有问题请继续反馈 :)
