### ISSUE TITLE
peeweedbevolve module

### ISSUE THREAD

**Issue by Zeroman** [reorx/xiami_exporter#7]
ModuleNotFoundError: No module named 'peeweedbevolve'

**Comment by Zeroman** [comment]
It is recommended to add 2 packages:
wheel
peewee-db-evolve

**Comment by reorx** [comment]
谢谢告知，peeweedbevolve 是之前用的一个库，忘了删掉；wheel 的话是 pip 自带，不被本项目直接引用。

已在 a9f49b3 中删除 peeweedbevolve import
